TheFinalreset/Models/Entities/Build.cs
using System.ComponentModel.DataAnnotations;

namespace TheFinalreset.Models.Entities
{
	public class Build
	{
		public int Id { get; set; }
		[Required]
		[StringLength(50)]
		public string Name { get; set; } = string.Empty;
		[StringLength(500)]
		public string Description { get; set; } = string.Empty;

		//Connects build to champion and item
		public int ChampionId { get; set; }
		public Champion? Champion { get; set; }
		public int ItemId { get; set; }
		public Item? Item { get; set; }
	}
}

TheFinalreset/Models/Entities/Champion.cs
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace TheFinalreset.Models.Entities
{
	public enum Role { Top, Middle, Jungle, Bottom, Support }
	public enum Difficulty { Low, Medium, High }
	public class Champion
	{
		public int Id { get; set; }
		[Required]
		[StringLength(50)]
		public string Name { get; set; } = string.Empty;
		public Role Role { get; set; }
		public Difficulty Difficulty { get; set; }

		//Connects champion to build
		public ICollection<Build> ChampionBuilds { get; set; } = new List<Build>();
	}
}

TheFinalreset/Models/Entities/Item.cs
namespace TheFinalreset.Models.Entities
{
	public class Item
	{
		public int Id { get; set; }
		public string Name { get; set; } = string.Empty;
		public string Description { get; set; } = string.Empty;
		public int AttackDamage { get; set; }
		public double AttackSpeed { get; set; }
		public double CriticalStrikeChance { get; set; }
		public double LifeSteal { get; set; }
		public double ArmorPenetration { get; set; }
		public int Lethality { get; set; }
		public int Cost { get; set; }

		//Connects item to build
		public ICollection<Build> ItemBuilds { get; set; } = new List<Build>();
	}
}

TheFinalreset/Models/ErrorViewModel.cs
namespace TheFinalreset.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

TheFinalreset/Models/ViewModels/BuildVM.cs
using TheFinalreset.Models.Entities;

namespace TheFinalreset.Models.ViewModels
{
	public class BuildVM
	{
		public Champion? Champion { get; set; }
		public Item? Item { get; set; }
	}
}

TheFinalreset/Controllers/BuildController.cs
using Microsoft.AspNetCore.Mvc;
using TheFinalreset.Models.ViewModels;
using TheFinalreset.Services;

namespace TheFinalreset.Controllers
{
	public class BuildController : Controller
	{
		private readonly IChampionRepository _championRepo;
		private readonly IItemRepository _itemRepo;
		private readonly IBuildRepository _buildRepo;

		public BuildController(IChampionRepository championRepo, IItemRepository itemRepo, IBuildRepository buildRepo)
		{
			_championRepo = championRepo;
			_itemRepo = itemRepo;
			_buildRepo = buildRepo;
		}

		public IActionResult Index()
		{
			return View();
		}

		public async Task<IActionResult> Create([Bind(Prefix = "id")] int championId, int itemId)
		{
			var champion = await _championRepo.ReadAsync(championId);
			if (champion == null)
			{
				return RedirectToAction("Index", "Champion");
			}

			var item = await _itemRepo.ReadAsync(itemId);
			if (item == null)
			{
				return RedirectToAction("Details", "Champion", new { id = championId });
			}

			var build = champion.ChampionBuilds.SingleOrDefault(i => i.ItemId == itemId);
			if (build != null)
			{
				return RedirectToAction("Details", "Champion", new { id = championId });
			}

			var buildVM = new BuildVM
			{
				Champion = champion,
				Item = item
			};
			return View(buildVM);
		}

		[HttpPost, ValidateAntiForgeryToken, ActionName("Create")]
		public async Task<IActionResult> CreateConfirmed(int championId, int itemId)
		{
			await _buildRepo.CreateAsync(championId, itemId);
			return RedirectToAction("Details", "Champion", new { id = championId });
		}
	}
}

TheFinalreset/Controllers/ChampionController.cs
using Microsoft.AspNetCore.Mvc;
using TheFinalreset.Services;

namespace TheFinalreset.Controllers
{
	public class ChampionController : Controller
	{
		private IChampionRepository _championRepo;

		public ChampionController(IChampionRepository championRepo)
		{
			_championRepo = championRepo;
		}

		public async Task<IActionResult> Index()
		{
			return View(await _championRepo.ReadAllAsync());
		}

		public async Task<IActionResult> Details(int id)
		{
			var champion = await _championRepo.ReadAsync(id);
			if (champion == null)
			{
				return RedirectToAction("Index");
			}
			return View(champion);
		}
	}
}

TheFinalreset/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TheFinalreset.Models;

namespace TheFinalreset.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

TheFinalreset/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using TheFinalreset.Services;

namespace TheFinalreset.Controllers
{
	public class ItemController : Controller
	{
		private IChampionRepository _championRepo;
		private readonly IItemRepository _itemRepo;

		public ItemController(IChampionRepository championRepo, IItemRepository itemRepo)
		{
			_championRepo = championRepo;
			_itemRepo = itemRepo;
		}

		public async Task<IActionResult> Index()
		{
			var allItems = await _itemRepo.ReadAllAsync();
			return View(allItems);
		}

		public async Task<IActionResult> AddItem([Bind(Prefix = "id")] int championId)
		{
			var champion = await _championRepo.ReadAsync(championId);
			if (champion == null)
			{
				return RedirectToAction("Index", "Champion");
			}
			var allItems = await _itemRepo.ReadAllAsync();
			var itemsAdded = champion.ChampionBuilds
			.Select(i => i.Item).ToList();
			var itemsNotAdded = allItems.Except(itemsAdded);
			ViewData["Champion"] = champion;
			return View(itemsNotAdded);
		}
	}
}

TheFinalreset/Views/Build/Create.cshtml
@model TheFinalreset.Models.ViewModels.BuildVM

<h3>
    Are you sure you want to add @Model!.Item!.Name to @Model!.Champion!.Name?
</h3>


<form asp-action="Create" id="formCreateBuild">
    <input type="hidden" name="championId" value="@Model.Champion.Id" />
    <input type="hidden" name="itemId" value="@Model.Item.Id" />
    <input type="submit" value="Add Item"/> |
    <a asp-action="AddItem" asp-controller="Item"
       asp-route-id="@Model!.Champion!.Id">Don't Add</a>
</form>

@section Scripts{
    @*<script defer type="module" src="~/js/build.js"></script>*@
}

TheFinalreset/Views/Champion/Details.cshtml
@model TheFinalreset.Models.Entities.Champion

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Champion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Difficulty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Difficulty)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="AddItem" asp-controller="Item" asp-route-id="@Model!.Id">Add Item</a> |
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

<h3>Added Items</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Decription
            </th>
            <th>
                Attack Damage
            </th>
            <th>
                Attack Speed
            </th>
            <th>
                Critical Strike 
            </th>
            <th>
                Life Steal
            </th>
            <th>
                Armor Penetration
            </th>
            <th>
                Lethality
            </th>
            <th>
                Cost
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model.ChampionBuilds)
            {
                <tr>
                    <td>
                        @item.Item!.Name
                    </td>
                    <td>
                        @item.Item!.Description
                    </td>
                    <td>
                        @item.Item!.AttackDamage
                    </td>
                    <td>
                        @item.Item!.AttackSpeed
                    </td>
                    <td>
                        @item.Item!.CriticalStrikeChance
                    </td>
                    <td>
                        @item.Item!.LifeSteal
                    </td>
                    <td>
                        @item.Item!.ArmorPenetration
                    </td>
                    <td>
                        @item.Item!.Lethality
                    </td>
                    <td>
                        @item.Item!.Cost
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        <a asp-action="additem" asp-controller="Build" asp-route-id="@Model!.Id" asp-route-courseId="@item.ItemId">Assign Item</a> |
                        <a asp-action="remove" asp-controller="Build" asp-route-id="@Model!.Id" asp-route-courseId="@item.ItemId">Remove Item</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

TheFinalreset/Views/Champion/Index.cshtml
@model IEnumerable<TheFinalreset.Models.Entities.Champion>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Difficulty)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Difficulty)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            </td>
        </tr>
}
    </tbody>
</table>

TheFinalreset/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TheFinalreset/Views/Item/AddItem.cshtml
@using TheFinalreset.Models.Entities
@model IEnumerable<TheFinalreset.Models.Entities.Item>

@{
    var champion = (Champion?)ViewData["Champion"];
    ViewData["Title"] = $"Add item for {champion!.Name}";
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AttackDamage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AttackSpeed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CriticalStrikeChance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LifeSteal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArmorPenetration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lethality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AttackDamage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AttackSpeed)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CriticalStrikeChance)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LifeSteal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ArmorPenetration)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Lethality)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cost)
                    </td>
                    <td>
                        <a asp-action="create" asp-controller="Build"
                            asp-route-id="@champion!.Id" 
                            asp-route-courseId="@item.Id">Add Item</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<div>
    <a asp-action="Details" asp-controller="Champion" asp-route-id="@champion.Id">Back to Champion Details</a>
</div>

TheFinalreset/Views/Item/Index.cshtml
@model IEnumerable<TheFinalreset.Models.Entities.Item>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AttackDamage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AttackSpeed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CriticalStrikeChance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LifeSteal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArmorPenetration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lethality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AttackDamage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AttackSpeed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CriticalStrikeChance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LifeSteal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArmorPenetration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lethality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            </td>
        </tr>
}
    </tbody>
</table>

TheFinalreset/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TheFinalreset</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TheFinalreset.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Champion" asp-action="Index">Champions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Items</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TheFinalreset - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>